"use client";

// Daily morning brief from AVA. Renders only between 6am and 11am local
// time, OR if the user hasn't seen today's brief yet (sessionStorage flag).
// Content is generated by /api/cron/cafe-am at 7am CDMX and exposed via
// the public /api/cafe-am GET endpoint.

import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { PlayerAvatar } from "@/components/PlayerAvatar";
import { PLAYERS, AI_PLAYER_ID } from "@/data/players";
import { useLocale } from "@/lib/i18n";
import { useHomeSnapshot } from "@/lib/home-snapshot";

const AI_PLAYER = PLAYERS.find(p => p.id === AI_PLAYER_ID)!;
const DISMISS_KEY = (date: string) => `q26:cafeam-dismissed:${date}`;
const SEEN_KEY = (date: string) => `q26:cafeam-seen:${date}`;

type Brief = {
  date: string;          // YYYY-MM-DD CDMX
  text: string;
  generatedAt: number;
};

type Response = { ok: boolean; brief: Brief | null };

function cdmxDate(): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Mexico_City",
    year: "numeric", month: "2-digit", day: "2-digit",
  }).format(new Date());
}

function cdmxHour(): number {
  // 24h hour in CDMX. Used to gate the "morning window".
  const parts = new Intl.DateTimeFormat("en-GB", {
    timeZone: "America/Mexico_City",
    hour: "2-digit", hour12: false,
  }).formatToParts(new Date());
  const h = parts.find(p => p.type === "hour")?.value ?? "0";
  return Number(h) || 0;
}

export function CafeAmCard() {
  const { t } = useLocale();
  const snapshot = useHomeSnapshot();
  const snapshotBrief = snapshot?.data?.cafeAm?.brief ?? null;
  const [brief, setBrief] = useState<Brief | null>(null);
  const [dismissed, setDismissed] = useState(false);
  const [shouldShow, setShouldShow] = useState(false);

  useEffect(() => {
    const today = cdmxDate();
    const hour = cdmxHour();
    // "Morning" = 6am-11am CDMX.
    const inMorning = hour >= 6 && hour < 11;
    let alreadySeen = false;
    let alreadyDismissed = false;
    try {
      alreadySeen = sessionStorage.getItem(SEEN_KEY(today)) === "1";
      alreadyDismissed = sessionStorage.getItem(DISMISS_KEY(today)) === "1";
    } catch {}
    if (alreadyDismissed) { setDismissed(true); return; }
    // Show inside the morning window; outside, only if the user hasn't seen
    // today's brief yet on this device (so latecomers still catch it).
    setShouldShow(inMorning || !alreadySeen);
  }, []);

  // Take the brief from the snapshot first; only fall back to our own fetch
  // when the home page hasn't mounted the provider (defensive).
  useEffect(() => {
    if (!shouldShow) return;
    if (snapshotBrief) {
      setBrief(snapshotBrief);
      try { sessionStorage.setItem(SEEN_KEY(snapshotBrief.date), "1"); } catch {}
    }
  }, [shouldShow, snapshotBrief]);

  useEffect(() => {
    if (!shouldShow) return;
    if (snapshot) return; // provider will hydrate brief via the effect above
    let cancelled = false;
    fetch("/api/cafe-am")
      .then(r => (r.ok ? r.json() : null))
      .then((j: Response | null) => {
        if (cancelled || !j?.ok || !j.brief) return;
        setBrief(j.brief);
        try { sessionStorage.setItem(SEEN_KEY(j.brief.date), "1"); } catch {}
      })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [shouldShow, snapshot]);

  if (!shouldShow || dismissed || !brief) return null;

  return (
    <section className="container-app pt-2 pb-4">
      <div
        className="rounded-3xl p-5 md:p-6 relative overflow-hidden ring-1 ring-amber-200/60"
        style={{
          background:
            "linear-gradient(135deg, color-mix(in srgb, #FFE07A 35%, transparent) 0%, color-mix(in srgb, #FFB347 24%, transparent) 60%, color-mix(in srgb, #FF7F11 14%, transparent) 100%)",
        }}
      >
        <button
          type="button"
          aria-label="dismiss"
          onClick={() => {
            setDismissed(true);
            try { sessionStorage.setItem(DISMISS_KEY(brief.date), "1"); } catch {}
          }}
          className="absolute top-3 right-3 w-7 h-7 rounded-full grid place-items-center bg-white/40 hover:bg-white/60 text-[#7C3F00]"
        >
          <X size={14} />
        </button>
        <div className="flex items-start gap-3">
          <PlayerAvatar player={AI_PLAYER} size={44} rounded="rounded-2xl" textClass="text-xl" tint={0.18} />
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-[11px] uppercase tracking-wider font-extrabold text-[#7C3F00]">
                ☕ {t("cafeAm.title")}
              </span>
              <span className="text-[10px] text-[#7C3F00]/70 tabular-nums">{brief.date}</span>
            </div>
            <p className="text-sm md:text-base leading-relaxed text-[#3b2a05] whitespace-pre-wrap">
              {brief.text}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
