[project]
name = "vertex-ai-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet>=0.27.6",
    "google-cloud-aiplatform>=1.84.0",
    "google-cloud-bigquery>=3.30.0",
    "google-genai>=1.5.0",
    "ipython>=9.0.2",
    "pandas>=2.2.3",
    "pip>=25.0.1",
    "pyarrow>=19.0.1",
]
