FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

COPY trainer/ trainer/

RUN apt-get update -y && \
     apt install python3 python3-pip -y && \
     apt-get install -y nvidia-container-toolkit-base

RUN pip install --upgrade pip
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 && \
    pip install pytorch_tabular[extra] && \
    pip install pandas gcsfs

CMD ["python3", "-m", "trainer.train"]