steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--single-branch', '--branch',
         'main', 'https://github.com/jchavezar/vertex-ai-samples.git',
         '--depth', '1',
         '--verbose']
    id: 'Clone Repository'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/vtxdemos/custom-trains/tf-pipe_preprocess_cpu:1.0', '-f', 'vertex-ai-samples/pipelines-flex/tensorflow/tabular/Dockerfile_train_[cpu]', 'vertex-ai-samples/pipelines-flex/tensorflow/tabular/.']
    id: 'Build Training Docker Image'
    waitFor: ['Clone Repository']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/vtxdemos/custom-trains/tf-pipe_preprocess_cpu:1.0']
    id: 'Push Training Docker Image'
    waitFor: ['Build Training Docker Image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/vtxdemos/builds/pipe-trigger:v2', '-f', 'vertex-ai-samples/pipelines-flex/tensorflow/tabular/Dockerfile_build', 'vertex-ai-samples/pipelines-flex/tensorflow/tabular/.']
    id: 'Build Pipeline Run Docker Image'
    waitFor: ['Clone Repository']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/vtxdemos/builds/pipe-trigger:v2']
    id: 'Push Pipeline Run Docker Image'
    waitFor: ['Build Pipeline Run Docker Image']

  - name: 'us-central1-docker.pkg.dev/vtxdemos/builds/pipe-trigger:v2'
    entrypoint: 'python'
    args: ['/app/pipeline.py']
    id: 'Execute Vertex Pipeline'
    waitFor: ['Push Pipeline Run Docker Image', 'Push Training Docker Image']
  
images: 
  - us-central1-docker.pkg.dev/vtxdemos/builds/pipe-trigger:v2