FROM python:3.10-slim

WORKDIR /app
COPY trainer trainer/

RUN pip install --upgrade pip
RUN pip install tensorflow && \
    pip install google-cloud-storage && \
    pip install pandas && \
    pip install gcsfs

CMD ["python", "-m", "trainer.train"]