apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    
    http {
      server {
        listen 8081;
        location /healthz {
          return 200;
        }
         location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }