apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: sql-backend-config
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 300
    port: 8080
    type: HTTP
    requestPath: /healthz