FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

COPY trainer/ trainer/

RUN apt-get update -y && \
     apt install python3 python3-pip -y && \
     apt-get install -y nvidia-container-toolkit-base

RUN pip install tensorflow && \
    pip install google-cloud-storage && \
    pip install pandas && \
    pip install gcsfs

CMD ["python3", "-m", "trainer.train"]