steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-f', 'multimodal-search/deploy/Dockerfile.ingest', '-t', 'gcr.io/$PROJECT_ID/envato-vibe-ingest:latest', '.']
images:
- 'gcr.io/$PROJECT_ID/envato-vibe-ingest:latest'
options:
  logging: CLOUD_LOGGING_ONLY
