[project]
name = "gen-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet>=0.27.6",
    "google-adk>=0.3.0",
    "google-cloud-bigquery>=3.31.0",
    "google-genai>=1.11.0",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "pip>=25.1",
    "pyarrow>=19.0.1",
]
