[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "google-cloud-secret-manager>=2.30.0",
    "google-genai>=2.19.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn>=0.52.4",
]
