[project]
name = "adk-enterprise-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "google-adk>=2.0.0",
    "google-genai>=2.20.0",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.52.4",
]
