import { X } from 'lucide-react';

interface Props {
  onClose: () => void;
}

export default function ExplainerOverlay({ onClose }: Props) {
  return (
    <div className="explainer-overlay" onClick={onClose}>
      <div className="explainer-panel" onClick={e => e.stopPropagation()}>
        <div className="explainer-header">
          <h2>How It Works</h2>
          <button className="detail-close" onClick={onClose}>
            <X size={20} />
          </button>
        </div>

        <div className="explainer-body">
          <section className="explainer-section">
            <div className="explainer-badge">Vibe Profile</div>
            <h3>Radar Scores (Energy, Sound, Aesthetic, Crowd, Walk-in)</h3>
            <p>
              Scores are generated by <strong>Gemini 2.5 Flash</strong> analyzing real
              Google Places customer reviews combined with venue metadata (categories,
              price tier, editorial summaries). Each dimension is scored 0-100 based on
              what actual visitors describe in their reviews.
            </p>
            <div className="explainer-source-tag">
              <span className="source-dot source-dot-reviews" />
              Google Places Reviews + Gemini 2.5 Flash
            </div>
          </section>

          <section className="explainer-section">
            <div className="explainer-badge">Who Goes Here</div>
            <h3>Character Archetypes</h3>
            <p>
              Three vivid NYC character sketches generated by <strong>Gemini 2.5 Flash</strong> based
              on the venue's vibe tags, categories, underground score, and customer reviews.
              These are AI-generated personas — creative interpretations, not demographic data.
            </p>
            <div className="explainer-source-tag">
              <span className="source-dot source-dot-ai" />
              AI-Generated (Gemini 2.5 Flash)
            </div>
          </section>

          <section className="explainer-section">
            <div className="explainer-badge">Neighborhood Signals</div>
            <h3>Reddit &amp; Instagram Posts</h3>
            <p>
              Real social media posts found via <strong>Google Search grounding</strong> — Gemini
              searches Reddit (r/nyc, r/FoodNYC, r/AskNYC) and Instagram for actual mentions
              of the venue. Posts marked with a <span className="verified-inline">&#10003;</span> are
              verified: the URL exists and the venue name appears in the text.
            </p>
            <div className="explainer-source-tag">
              <span className="source-dot source-dot-reddit" />
              Reddit + Instagram via Google Search Grounding
            </div>
          </section>

          <section className="explainer-section">
            <div className="explainer-badge">Underground Score</div>
            <h3>The Hexagon Number (0-100)</h3>
            <p>
              A <strong>deterministic score</strong> — no AI involved. Computed from hard data:
            </p>
            <ul className="explainer-factors">
              <li><strong>Review count</strong> — fewer reviews = more underground (up to -50)</li>
              <li><strong>Chain detection</strong> — known franchises get penalized (-60)</li>
              <li><strong>Listicle appearances</strong> — "top 10 best" lists = mainstream (-25)</li>
              <li><strong>Reddit mentions</strong> — organic local word-of-mouth (+25)</li>
              <li><strong>Hidden gem signal</strong> — low reviews + high rating (+15)</li>
            </ul>
            <div className="explainer-source-tag">
              <span className="source-dot source-dot-algo" />
              Deterministic Algorithm (no AI)
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
