# -*- coding: utf-8 -*-
"""Gemini Enterprise streamAssist API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8o2op3mYmMtulJ24nloiG4bgRg9o3wK

Copyright 2026 Google, LLC. This software is provided as-is, without
warranty or representation for any use or purpose. Your use of it is
subject to your agreement with Google.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

# Gemini Enterprise API Setup Guide
Code and instructions below below accompany the guide to [Embed Gemini Enterprise API in Apps](https://docs.google.com/document/d/1W4-GjLp2hiCQt_b2Zmb_tv4QUIZ6u33Yg67BZN8Hu3o)

Direct questions and feedback to @artw

# Authorization Setup for API access
Add an OAuth 2.0 client with proper scopes and redirect URL.

Example below is based on [Google's OAuth 2.0 client](https://support.google.com/googleapi/answer/6158849):
- From the GCP console, search for "OAuth consent screen"
- Create an OAuth 2.0 client for Web application
- Add the redirect URL specified above
- Click **Create**
- Download the `client_secret.json` and upload it here
- Run the Python script below to obtain the authorization URI

For other 3rd party OAuth clients, follow their documentation to obtain authorization information.
"""

import google.oauth2.credentials
import google_auth_oauthlib.flow

scopes=[
    'https://www.googleapis.com/auth/cloud-platform',
    'https://www.googleapis.com/auth/cloud_search.query',
    'https://www.googleapis.com/auth/discoveryengine.assist.readwrite',
    'https://www.googleapis.com/auth/discoveryengine.readwrite',
    'https://www.googleapis.com/auth/gmail.modify',
    'https://www.googleapis.com/auth/gmail.send',
    'https://www.googleapis.com/auth/gmail.labels',
    'https://www.googleapis.com/auth/gmail.readonly',
]

redirect_uri = 'https://127.0.0.1' #redirect_uri = 'https://your.actual.handler.com'

# Required, call the from_client_secrets_file method to retrieve the client ID from a
# client_secret.json file. The client ID (from that file) and access scopes are required. (You can
# also use the from_client_config method, which passes the client configuration as it originally
# appeared in a client secrets file but doesn't access the file itself.)
# Scopes: https://developers.google.com/identity/protocols/oauth2/scopes
client_secret_json = '/content/client_secret_2_146012503832-jmpnc66qndhg1kvlkkpiep3784a1s38e.apps.googleusercontent.com.json'
flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(client_secret_json,
    scopes=scopes)

# Required, indicate where the API server will redirect the user after the user completes
# the authorization flow. The redirect URI is required. The value must exactly
# match one of the authorized redirect URIs for the OAuth 2.0 client, which you
# configured in the API Console. If this value doesn't match an authorized URI,
# you will get a 'redirect_uri_mismatch' error.
flow.redirect_uri = redirect_uri

# Generate URL for request to Google's OAuth 2.0 server.
# Use kwargs to set optional request parameters.
authorization_url, state = flow.authorization_url(
    # Recommended, enable offline access so that you can refresh an access token without
    # re-prompting the user for permission. Recommended for web server apps.
    access_type='offline',
    # Optional, enable incremental authorization. Recommended as a best practice.
    include_granted_scopes='true',
    # Optional, if your application knows which user is trying to authenticate, it can use this
    # parameter to provide a hint to the Google Authentication Server.
    login_hint='hint@example.com',
    # Optional, set prompt to 'consent' will prompt the user for consent
    prompt='consent')
print(authorization_url)

"""1. Click and authorize the output link above
2. After consenting, it will redirect to a blank page for testing purposes.
3. Copy and paste the URL from the blank page to `authorization_response` in the next code block
"""

from urllib.parse import urlparse, parse_qs

authorization_response = '''
https://127.0.0.1/?state=vRGEylJzfWxVlMcU4ZFykGng0J5mDf&iss=https://accounts.google.com&code=4/0AfrIepAYgoMre5QqI9MwmOMXU-nCL0f_oqTDHWzujTixMVcUUiXByXXR5DGt1N4qpdLR8Q&scope=https://www.googleapis.com/auth/cloud-platform%20https://www.googleapis.com/auth/cloud_search.query%20https://www.googleapis.com/auth/discoveryengine.assist.readwrite%20https://www.googleapis.com/auth/discoveryengine.readwrite%20https://www.googleapis.com/auth/gmail.modify%20https://www.googleapis.com/auth/gmail.send%20https://www.googleapis.com/auth/gmail.labels%20https://www.googleapis.com/auth/gmail.readonly
'''.strip()

# 1. Parse the full URL into components
parsed_url = urlparse(authorization_response)

# 2. Extract the query string part
query_string = parsed_url.query
print(f"Query String: {query_string}")

# 3. Parse the query string into a dictionary
# parse_qs returns a dictionary where values are lists
query_params = parse_qs(query_string)
print(f"Query Parameters (full): {query_params}")

# 4. Access specific parameters
# For a single value, you can access the first element of the list
state = query_params.get('state', [''])[0]
print(state)

flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
    client_secret_json,
    scopes=scopes,
    state=state
)
flow.redirect_uri = redirect_uri
flow.fetch_token(authorization_response=authorization_response)

# Store the credentials in browser session storage, but for security: client_id, client_secret,
# and token_uri are instead stored only on the backend server.
credentials = flow.credentials
#print('token', credentials.token)
#print('refresh_token', credentials.refresh_token)
#print('granted_scopes', credentials.granted_scopes)

# For 3P federated connectors, get names and specs

import requests

PROJECT_NUMBER = "146012503832"
GE_APP = "artw_1767828836981"

headers = {
    "Authorization": f"Bearer {credentials.token}",
    "Content-Type": "application/json",
}

url = f"https://discoveryengine.googleapis.com/v1alpha/projects/{PROJECT_NUMBER}/locations/global/collections/default_collection/engines/{GE_APP}/widgetConfigs/default_search_widget_config"

response = requests.get(url, headers=headers)
collections = response.json().get('collectionComponents')
collection_name = collections[0].get('name')
dataStoreSpecs = [
    {'dataStore':r['name']}
    for r in collections[0].get('dataStoreComponents')
]
print(collection_name)
print(dataStoreSpecs)

"""For 3P federated connectors, perform any additional authorization required by those services
1. For example, based on the scopes and redirect uri, the authorization URI will look like:
https://auth.atlassian.com/authorize?audience=api.atlassian.com&client_id=pKDZBjNKfqygg8nnA2SyFqbHOm9ghOtW&scope=read%3Ajira-user%20read%3Ajira-work&redirect_uri=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Foauth-redirect&response_type=code&prompt=consent
2. We need to add `offline_access` to it:
https://auth.atlassian.com/authorize?audience=api.atlassian.com&client_id=pKDZBjNKfqygg8nnA2SyFqbHOm9ghOtW&scope=read%3Ajira-user%20read%3Ajira-work%20offline_access&redirect_uri=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Foauth-redirect&response_type=code&prompt=consent
3. Open the link in a new tab and consent
4. [Optional] Copy the resulting URL in the browser and paste it in `fullRedirectUri` below
"""

import requests

url = f'https://discoveryengine.googleapis.com/v1alpha/{collection_name}/dataConnector:acquireAndStoreRefreshToken'
headers = {
    "Authorization": f"Bearer {credentials.token}",
    "Content-Type": "application/json",
}

fullRedirectUri = '''
https://vertexaisearch.cloud.google.com/oauth-redirect?code=eyJraWQiOiJBVVRIX0NPREUtZTRlN2QwZjktNmMzNS00ZTE3LWI4NzQtODdjYTIwYWVkODNjIiwiYWxnIjoiSFMyNTYifQ.eyJqdGkiOiJjYTk4NjQyZC1kNWM0LTQ4ZDUtYTFkMy1jNjdiNWMzODE1OTIiLCJzdWIiOiI3MTIwMjA6Njc1NzVlNzUtY2Y3OC00ZTEyLWI0ZDYtYTU2NjU0ZWFhOTk1IiwibmJmIjoxNzcyNjkzNzU1LCJpc3MiOiJhdXRoLmF0bGFzc2lhbi5jb20iLCJpYXQiOjE3NzI2OTM3NTUsImV4cCI6MTc3MjY5NDA1NSwiYXVkIjoicEtEWkJqTktmcXlnZzhubkEyU3lGcWJIT205Z2hPdFciLCJjbGllbnRfYXV0aF90eXBlIjoiUE9TVCIsImh0dHBzOi8vaWQuYXRsYXNzaWFuLmNvbS92ZXJpZmllZCI6dHJ1ZSwiaHR0cHM6Ly9pZC5hdGxhc3NpYW4uY29tL3VqdCI6ImNhOTg2NDJkLWQ1YzQtNDhkNS1hMWQzLWM2N2I1YzM4MTU5MiIsInNjb3BlIjpbInJlYWQ6amlyYS13b3JrIiwib2ZmbGluZV9hY2Nlc3MiLCJyZWFkOmppcmEtdXNlciJdLCJodHRwczovL2lkLmF0bGFzc2lhbi5jb20vYXRsX3Rva2VuX3R5cGUiOiJBVVRIX0NPREUiLCJodHRwczovL2lkLmF0bGFzc2lhbi5jb20vaGFzUmVkaXJlY3RVcmkiOnRydWUsImh0dHBzOi8vaWQuYXRsYXNzaWFuLmNvbS9zZXNzaW9uX2lkIjoiYTQwNDAwNjQtZjY2YS00NGM4LTkwMGMtOGEzZTlmYjU4NWFiIiwiaHR0cHM6Ly9pZC5hdGxhc3NpYW4uY29tL3Byb2Nlc3NSZWdpb24iOiJ1cy13ZXN0LTIifQ.9Wx--6MGo17GxBdnJkgOgGclwpUil7ulgC0ph50St-E
'''.strip()

data = {
    "scopes": [
        'read:jira-work',
        'read:jira-user',
        'offline_access', #required additional scope
    ],
    "fullRedirectUri": fullRedirectUri,
}
response = requests.post(url, headers=headers, json=data)
print(response.text)

# Determine the assistant you want to chat with
# https://docs.cloud.google.com/gemini/enterprise/docs/reference/rest/v1alpha/projects.locations.collections.engines.assistants/list

import requests

url = f"https://discoveryengine.googleapis.com/v1alpha/projects/{PROJECT_NUMBER}/locations/global/collections/default_collection/engines/{GE_APP}/assistants"

headers = {
    "Authorization": f"Bearer {credentials.token}",
    "Content-Type": "application/json",
}

response = requests.get(url, headers=headers)
asst = response.json().get('assistants')[0].get('name')
print(asst)

q = "What jira items are assigned to me?"

# Run the chat
# https://docs.cloud.google.com/gemini/enterprise/docs/reference/rest/v1alpha/projects.locations.collections.engines.assistants/streamAssist

import requests

url = f"https://discoveryengine.googleapis.com/v1alpha/{asst}:streamAssist"

headers = {
    "Authorization": f"Bearer {credentials.token}",
    "Content-Type": "application/json"
}


data = {
    "query": {
        'text': q,
    },
    "toolsSpec": {
        'vertexAiSearchSpec': {
             "dataStoreSpecs": dataStoreSpecs,
         }
    },
#    "session": f"projects/{PROJECT_NUMBER}/locations/global/collections/default_collection/engines/{GE_APP}/sessions/-",
}

response = requests.post(url, headers=headers, json=data)

# Get the final response
response.json()[-1]

# Continue the chat conversation
sessionName = response.json()[-1]['sessionInfo']['session']
queryId = response.json()[-1]['sessionInfo']['queryId']