import json
from pathlib import Path

# Multi-Source Daily USD/JPY Rates (Sept 14-28, 2026):
# 1. ecb: Official ECB / Frankfurter Reference Rate (16:00 CET)
# 2. yahoo_ny: Yahoo Finance (JPY=X) Spot FX NY 17:00 EDT Close
# 3. currency_api: Open Interbank Currency-API (@fawazahmed0/currency-api) Daily Close
FX_MULTI_SOURCES = {
    "2026-09-14": {"ecb": 154.5500, "yahoo_ny": 154.4220, "currency_api": 154.0657},
    "2026-09-15": {"ecb": 155.0000, "yahoo_ny": 155.2870, "currency_api": 154.7027},
    "2026-09-16": {"ecb": 155.0500, "yahoo_ny": 156.0290, "currency_api": 155.3610},
    "2026-09-17": {"ecb": 155.6900, "yahoo_ny": 156.1590, "currency_api": 156.0927},
    "2026-09-18": {"ecb": 157.8900, "yahoo_ny": 157.0090, "currency_api": 157.0124},
    "2026-09-19": {"ecb": 157.8900, "yahoo_ny": 157.0090, "currency_api": 156.9048},
    "2026-09-20": {"ecb": 157.8900, "yahoo_ny": 157.0460, "currency_api": 156.8685},
    "2026-09-21": {"ecb": 157.2700, "yahoo_ny": 157.3610, "currency_api": 157.0249},
    "2026-09-22": {"ecb": 157.1800, "yahoo_ny": 157.4740, "currency_api": 157.5216},
    "2026-09-23": {"ecb": 157.9200, "yahoo_ny": 158.2700, "currency_api": 157.6250},
    "2026-09-24": {"ecb": 158.8500, "yahoo_ny": 158.8420, "currency_api": 157.9883},
    "2026-09-25": {"ecb": 157.5900, "yahoo_ny": 157.4450, "currency_api": 158.3719},
    "2026-09-26": {"ecb": 157.5900, "yahoo_ny": 157.4450, "currency_api": 157.2952},
    "2026-09-27": {"ecb": 157.5900, "yahoo_ny": 157.4630, "currency_api": 157.2950},
    "2026-09-28": {"ecb": 156.8800, "yahoo_ny": 157.3760, "currency_api": 157.7370},
}

FX_RATES = {k: v["ecb"] for k, v in FX_MULTI_SOURCES.items()}

# 24 Verified Digital / Email & Card-Statement Trip Expenses (Gmail + Amex *4002 + BofA Visa *8577 via @Google Wallet)
DIGITAL_EXPENSES = [
    {
        "page": 101,
        "display_id": "T-01",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-14",
        "time": "16:26",
        "merchant_jp": "デルタ航空 (Delta Air Lines — Conf #HUWJV4)",
        "merchant_en": "Delta Air Lines — Round-Trip NYC ⇄ Tokyo Haneda (Conf #HUWJV4)",
        "item_kanji": "往復航空券 LGA→DTW→HND / HND→SEA→JFK (デルタ・コンフォートプラス #0062464561695)",
        "item_en": "Round-Trip Airfare: DL1078/DL275 (LGA→DTW→HND) & DL166/DL415 (HND→SEA→JFK) — Delta Comfort+",
        "description_en": "Ticket #0062464561695 (SkyMiles #9441550887 Platinum Medallion). Outbound: DL1078 (LGA→DTW, Seat 11E) + DL275 (DTW→HND, Seat 32G). Return Sep 29: DL166 (HND→SEA, Seat 30E) + DL415 (SEA→JFK, Seat 11F). Total Ticket $1,417.93 minus $350.00 Delta eCredit (#0060726948967) = $1,067.93 net billed natively in USD to Amex *4002.",
        "category": "Flights & Airfare",
        "jpy_amount": 0,
        "usd_direct": 1067.93,
        "usd_charged": 1067.93,
        "card_status": "POSTED",
        "ecredit_applied_usd": 350.00,
        "gross_ticket_usd": 1417.93,
        "payment_method": "Amex *4002 (Posted, +$350 eCredit)",
        "card_network": "Amex",
        "card_mask": "AX***********4002",
        "receipt_ref": "Conf #HUWJV4 / Amex CSV 09/15/2026 / Gmail 1a0a2071458ab89d",
    },
    {
        "page": 102,
        "display_id": "T-02",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": "T-03",
        "date": "2026-09-19",
        "time": "17:34",
        "merchant_jp": "オールデイプレイス渋谷 (all day place shibuya — Booking.com)",
        "merchant_en": "all day place shibuya Hotel (Booking.com #5147776147 — Initial 6-Night Charge)",
        "item_kanji": "宿泊代金（6泊・コンパクト禁煙・朝食付）Booking.com事前決済",
        "item_en": "6-Night Hotel Pre-Payment (Sep 23–29, Compact Non-Smoking w/ Breakfast, Gross ¥220,259 − ¥24,028 Booking.com Subsidy)",
        "description_en": "Booking.com Conf #5147776147 (PIN 7343, Property Conf #202624367). Original 6-night stay (Sep 23–29): Property rate ¥220,259 minus ¥24,028 paid by Booking.com = ¥196,231 JPY billed. Amex *4002 posted $1,252.11 USD (effective rate ¥156.7203/$ vs. ECB ¥157.89/$ [+$9.28 / +0.75%], Yahoo NY Close ¥157.009/$ [+$2.30 / +0.18%], Currency-API ¥156.905/$ [+$1.47 / +0.12%]).",
        "category": "Hotel & Lodging",
        "jpy_amount": 196231,
        "usd_direct": None,
        "usd_charged": 1252.11,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Booking #5147776147 / Amex CSV 09/19/2026 / Gmail 1a0ba4e1341c440f",
    },
    {
        "page": 108,
        "display_id": "T-08",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-20",
        "time": "19:27",
        "merchant_jp": "KITTY in NY (日本旅行中の愛猫Michiペットシッター7日間)",
        "merchant_en": "KITTY in NY — Pet Sitting for Michi During Japan Trip (PayPal #24571)",
        "item_kanji": "愛猫Michiシッター訪問7回（9/22火〜9/28月・1日1回訪問）",
        "item_en": "Michi Cat Sitting Service — 7 Daily Visits (Tue Sep 22 – Mon Sep 28, 2026)",
        "description_en": "PayPal Invoice #24571 paid to KITTY in NY for 7 once-per-day cat-sitting visits for Michi during the Tokyo trip (Tue Sep 22 – Mon Sep 28, 2026). Billed natively in USD ($70.00) on American Express *4002.",
        "category": "Trip Logistics & Pet Care",
        "jpy_amount": 0,
        "usd_direct": 70.00,
        "usd_charged": 70.00,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted PayPal)",
        "card_network": "Amex",
        "card_mask": "AMEX x-4002",
        "receipt_ref": "PayPal #24571 / Amex CSV 09/20/2026 / Gmail 1a0c1ca6b748b31a",
    },
    {
        "page": 103,
        "display_id": "T-03",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": "T-02",
        "date": "2026-09-22",
        "time": "15:22",
        "merchant_jp": "オールデイプレイス渋谷 (Booking.com 1泊短縮返金クレジット)",
        "merchant_en": "all day place shibuya Hotel (Booking.com #5147776147 — 1-Night Refund Credit)",
        "item_kanji": "日程変更による1泊分返金クレジット（9/24〜9/29の5泊・708号室へ変更）",
        "item_en": "1-Night Hotel Refund Credit (Shortened to 5 Nights Sep 24–29 due to Flight Delay, Room #708)",
        "description_en": "After outbound flight DL1078 was delayed on Sep 22, arrival shifted to Sep 24 (5 nights: Sep 24–29, Room #708). Property total reduced from ¥220,259 to ¥190,603 (-¥29,656 gross; -¥26,421 net customer refund after pro-rated Booking.com discount). Amex *4002 credited -$168.24 USD (effective rate ¥157.0435/$), bringing Net 5-Night Hotel Spend to ¥169,810 / $1,083.87 USD.",
        "category": "Hotel & Lodging",
        "jpy_amount": -26421,
        "usd_direct": None,
        "usd_charged": -168.24,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted Credit)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex Credit -$168.24 / CSV 09/22/2026 / Gmail 1a0cf8aa5764f126",
    },
    {
        "page": 104,
        "display_id": "T-04",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-22",
        "time": "05:56",
        "merchant_jp": "Lyft (米国ニューヨーク・ラガーディア空港送迎 #1 — 運転手 Mohammad)",
        "merchant_en": "Lyft — NYC to LaGuardia Airport (LGA) Ride #1 (Driver: Mohammad)",
        "item_kanji": "Lyft Extra Comfort 空港配車 (511 W 38th St → LGA Airport, 9.17マイル)",
        "item_en": "Lyft Extra Comfort to LGA Airport (511 W 38th St → 10702 Grand Central Pkwy LGA, 9.17 mi, 37m 51s)",
        "description_en": "Airport ride #1 to LaGuardia (LGA) for initial Sep 22 departure attempt (05:56 AM – 06:34 AM): Extra Comfort Fare $52.16 + LGA Airport Fee $3.50 + NY Sales Tax $4.05 + Congestion Surcharges $4.25 + Black Car Fund $0.95 − Promo -$10.00 = $54.91 USD. Billed natively in USD on Visa *6977.",
        "category": "Airport & Ground Transport",
        "jpy_amount": 0,
        "usd_direct": 54.91,
        "usd_charged": 54.91,
        "card_status": "POSTED",
        "payment_method": "Visa *6977 (Posted)",
        "card_network": "Visa",
        "card_mask": "Visa *6977",
        "receipt_ref": "Lyft Receipt #2266740411546301274 / Gmail 1a0c96eecc42d315",
    },
    {
        "page": 105,
        "display_id": "T-05",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-22",
        "time": "14:05",
        "merchant_jp": "Ubigi / Transatel (NTTグループ 日本10GB eSIMデータ通信)",
        "merchant_en": "Ubigi (Transatel / NTT) — Japan 10 GB eSIM Data Plan",
        "item_kanji": "Ubigi 日本データ通信プラン JAPAN 10 GB (eSIM #8988247000146290003)",
        "item_en": "JAPAN 10 GB Prepaid eSIM Data Plan ($14.00 − $1.40 WELCOME10 Promo)",
        "description_en": "Pre-departure Japan mobile data eSIM plan (10 GB, SIM Ref: 8988247000146290003). Billed natively in USD ($12.60) via Stripe Receipt #1624-7662 on American Express *4002.",
        "category": "Connectivity & eSIM",
        "jpy_amount": 0,
        "usd_direct": 12.60,
        "usd_charged": 12.60,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted)",
        "card_network": "Amex",
        "card_mask": "Amex *4002",
        "receipt_ref": "Stripe #1624-7662 / Amex CSV 09/22/2026 / Gmail 1a0c902a8f0beb1f",
    },
    {
        "page": 106,
        "display_id": "T-06",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-23",
        "time": "05:54",
        "merchant_jp": "Lyft (米国ニューヨーク・ラガーディア空港送迎 #2 — 運転手 Harle)",
        "merchant_en": "Lyft — NYC to LaGuardia Airport (LGA) Ride #2 (Driver: Harle)",
        "item_kanji": "Lyft Extra Comfort 空港配車 (511 W 38th St → LGA Airport, 10.26マイル・トンネル通行料・チップ込)",
        "item_en": "Lyft Extra Comfort to LGA Airport (511 W 38th St → 10702 Grand Central Pkwy LGA, 10.26 mi, incl. Tunnel Toll & Tip)",
        "description_en": "Airport ride #2 to LaGuardia (LGA) for rescheduled Sep 23 departure (05:54 AM – 06:32 AM): Extra Comfort Fare $44.71 + Queens Midtown Tunnel Toll $7.46 + LGA Airport Fee $3.50 + NY Sales Tax $4.05 + Congestion Surcharges $4.25 + Black Car Fund $0.95 + Tip $9.74 − Promo -$10.00 = $64.66 USD. Billed natively in USD on Visa *6977.",
        "category": "Airport & Ground Transport",
        "jpy_amount": 0,
        "usd_direct": 64.66,
        "usd_charged": 64.66,
        "card_status": "POSTED",
        "payment_method": "Visa *6977 (Posted)",
        "card_network": "Visa",
        "card_mask": "Visa *6977",
        "receipt_ref": "Lyft Receipt #2267110936961857110 / Gmail 1a0cdec85d936c0d",
    },
    {
        "page": 109,
        "display_id": "T-09",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-23",
        "time": "Layover",
        "merchant_jp": "iStore Express — 米国デトロイト空港 (DTW Layover)",
        "merchant_en": "iStore Express — Detroit Metro Airport (DTW Layover En Route to Tokyo)",
        "item_kanji": "デトロイト空港トランジット（トラベルピロー／ガジェット類）GglPay DTW ISTORE EX",
        "item_en": "DTW Airport Layover Purchase at iStore Express (Travel Pillow / Flight Accessories)",
        "description_en": "Purchased during the Detroit Metropolitan Airport (DTW) layover between flight DL1078 (LGA→DTW) and DL275 (DTW→HND) on Sep 23, 2026. Billed natively in USD ($52.99) via Google Pay on American Express *4002.",
        "category": "Airport & Ground Transport",
        "jpy_amount": 0,
        "usd_direct": 52.99,
        "usd_charged": 52.99,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted Google Pay)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex CSV 09/23/2026 (GglPay DTW ISTORE EXDETROIT MI)",
    },
    {
        "page": 110,
        "display_id": "T-10",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-23",
        "time": "Layover",
        "merchant_jp": "Gameway — 米国デトロイト空港ゲーミングラウンジ (DTW Layover)",
        "merchant_en": "Gameway — Detroit Metro Airport Gaming Lounge (DTW Layover — 2 Charges)",
        "item_kanji": "デトロイト空港 Gameway ラウンジ利用 ($4.65 + $11.64)",
        "item_en": "DTW Airport Gameway Lounge Session & Refreshments ($4.65 + $11.64 = $16.29)",
        "description_en": "Two Google Pay charges ($4.65 and $11.64 = $16.29 total) at Gameway DTW Airport Gaming Lounge during the Detroit layover before boarding DL275 to Tokyo Haneda. Billed natively in USD on American Express *4002.",
        "category": "Airport & Ground Transport",
        "jpy_amount": 0,
        "usd_direct": 16.29,
        "usd_charged": 16.29,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted Google Pay)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex CSV 09/23/2026 (2× GglPay GAMEWAY DTW 2DETROIT MI)",
    },
    {
        "page": 111,
        "display_id": "T-11",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-24",
        "time": "Dinner",
        "merchant_jp": "渋谷寿司 神南 (SHIBUYA SUSHI JINNAN TOKYO JP)",
        "merchant_en": "Shibuya Sushi Jinnan (Tokyo — Card Statement Record)",
        "item_kanji": "渋谷・神南 寿司ディナー（アメックス明細計上分）",
        "item_en": "Sushi Dinner at Shibuya Sushi Jinnan (Tokyo Day 1)",
        "description_en": "Posted on American Express *4002 on 09/24/2026: SHIBUYA SUSHI JINNANTOKYO JP for $125.28 USD (approx. ¥19,667 JPY at Amex Sep 24 effective rate ¥156.98/$). Discovered via Amex statement audit (no paper receipt in PDF).",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 0,
        "usd_direct": 125.28,
        "usd_charged": 125.28,
        "fx_mode_override": "STATEMENT_ONLY_USD",
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted — Card Statement Only)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex CSV 09/24/2026 (SHIBUYA SUSHI JINNANTOKYO JP)",
    },
    {
        "page": 112,
        "display_id": "T-12",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-25",
        "time": "Daytime",
        "merchant_jp": "CAFE MONOCHROME 渋谷 / Mikkeller KIOSK Bar / SHE WOLF DINER (渋谷カフェ・ダイナー3件)",
        "merchant_en": "Shibuya Cafes & Diner: Cafe Monochrome ($6.26) + Mikkeller Kiosk ($8.86) + She Wolf Diner ($18.79)",
        "item_kanji": "渋谷カフェ＆ダイナー3軒（CAFE MONOCHROME・Mikkeller KIOSK・SHE WOLF DINER）",
        "item_en": "3 Shibuya Dining/Cafe Stops on Sep 25: Cafe Monochrome ($6.26) + Mikkeller Kiosk Bar ($8.86) + She Wolf Diner ($18.79)",
        "description_en": "Three posted Tokyo dining/cafe charges on Amex *4002 on 09/25/2026 without paper receipts in the PDF: (1) CAFE MONOCHROME AIR TOKYO JP ($6.26), (2) Mikkeller KIOSK Bar at all day place shibuya 1F ($8.86), (3) SHE WOLF DINER AIR TOKYO JP ($18.79). Total: $33.91 USD (Posted).",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 0,
        "usd_direct": 33.91,
        "usd_charged": 33.91,
        "fx_mode_override": "STATEMENT_ONLY_USD",
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted — Card Statement Only)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex CSV 09/25/2026 (3× Tokyo Dining/Cafe Charges)",
    },
    {
        "page": 113,
        "display_id": "T-13",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-25",
        "time": "Transit",
        "merchant_jp": "Uber (東京・空港移動ライドシェア — 9/25計上分)",
        "merchant_en": "Uber — Tokyo Ground Transportation (Sep 25 Posted Charge)",
        "item_kanji": "Uber 配車利用代金（9/25 アメックス明細計上分）",
        "item_en": "Uber Ride(s) on Sep 25, 2026 ($185.44 USD Posted on Amex *4002)",
        "description_en": "Posted Uber charge on American Express *4002 on 09/25/2026 for $185.44 USD (plus pending Sep 28 Uber charges of $39.05 and $42.59 tracked in T-18).",
        "category": "Airport & Ground Transport",
        "jpy_amount": 0,
        "usd_direct": 185.44,
        "usd_charged": 185.44,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex CSV 09/25/2026 (UBER $185.44)",
    },
    {
        "page": 114,
        "display_id": "T-14",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-25",
        "time": "Dinner",
        "merchant_jp": "鳥道酒場 (RAKUTENPAY TORIMICHISAKAB — 渋谷・新宿 焼き鳥居酒屋)",
        "merchant_en": "Torimichi Sakaba Yakitori Izakaya (Rakuten Pay — Pending on Amex *4002)",
        "item_kanji": "鳥道酒場 飲食代金（楽天ペイ決済・アメックス保留中）",
        "item_en": "Dinner & Drinks at Torimichi Sakaba Izakaya ($94.40 USD Pending on Amex *4002)",
        "description_en": "Pending charge on American Express *4002 (Sep 25, 2026): RAKUTENPAY TORIMICHISAKAB for $94.40 USD (approx. ¥14,944 JPY). Discovered on live Amex Account Activity tab.",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 0,
        "usd_direct": 94.40,
        "usd_charged": 94.40,
        "fx_mode_override": "STATEMENT_ONLY_USD",
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending — Card Statement Only)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex Live Activity 09/25/2026 (RAKUTENPAY TORIMICHISAKAB)",
    },
    {
        "page": 115,
        "display_id": "T-15",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-25",
        "time": "Shopping",
        "merchant_jp": "ブルガリ 東京 (Bvlgari — BofA Visa *8577 決済分)",
        "merchant_en": "Bvlgari Tokyo Boutique (Pending on BofA Visa *8577 via @Google Wallet)",
        "item_kanji": "BVLGARI（ブルガリ）ラグジュアリー購入代金（BofA Visa *8577 保留中）",
        "item_en": "Bvlgari Luxury Boutique Purchase in Tokyo ($3,169.17 USD Pending on BofA Visa *8577)",
        "description_en": "Discovered via @Google Wallet (Plaid link to Bank of America Premium Rewards Visa Signature *8577) on Sep 25, 2026: Bvlgari pending purchase of $3,169.17 USD (approx. ¥500,000 JPY).",
        "category": "Apparel & Footwear",
        "jpy_amount": 0,
        "usd_direct": 3169.17,
        "usd_charged": 3169.17,
        "fx_mode_override": "STATEMENT_ONLY_USD",
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "BofA Visa *8577 (Pending — @Google Wallet)",
        "card_network": "Visa",
        "card_mask": "BofA Visa *8577",
        "receipt_ref": "Google Wallet / BofA *8577 09/25/2026 (Bvlgari $3,169.17)",
    },
    {
        "page": 107,
        "display_id": "T-07",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-26",
        "time": "23:09",
        "merchant_jp": "Ubigi / Transatel (NTTグループ 日本5GB eSIM追加チャージ)",
        "merchant_en": "Ubigi (Transatel / NTT) — Japan 5 GB eSIM Data Top-Up",
        "item_kanji": "Ubigi 日本データ通信プラン追加チャージ JAPAN 5 GB (eSIM #8988247000146290003)",
        "item_en": "JAPAN 5 GB Prepaid eSIM Data Top-Up Plan (Stripe Receipt #1983-2155)",
        "description_en": "Mid-trip 5 GB Japan eSIM data reload purchased in Tokyo. Billed natively in USD ($10.00) via Stripe Receipt #1983-2155 on American Express *4002 (Apple Pay).",
        "category": "Connectivity & eSIM",
        "jpy_amount": 0,
        "usd_direct": 10.00,
        "usd_charged": 10.00,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted)",
        "card_network": "Amex",
        "card_mask": "Amex *4002",
        "receipt_ref": "Stripe #1983-2155 / Amex CSV 09/26/2026 / Gmail 1a0de0dbc23c4f29",
    },
    {
        "page": 116,
        "display_id": "T-16",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-26",
        "time": "Convenience",
        "merchant_jp": "セブン-イレブン 2件 & PICNICRAND AIR (アメックス明細分)",
        "merchant_en": "7-Eleven Japan (2× Visits: $2.61 Posted + $4.70 Pending) + Picnicrand Air ($1.04 Pending)",
        "item_kanji": "セブン-イレブン 2回（$2.61 + $4.70）＋ PICNICRAND AIR（$1.04）",
        "item_en": "3 Small Tokyo Convenience/Vending Charges on Sep 26 ($2.61 Posted + $4.70 Pending + $1.04 Pending = $8.35)",
        "description_en": "Three small Tokyo charges on American Express *4002 on Sep 26, 2026 without paper receipts in the PDF: (1) SEVEN ELEVEN * JP ($2.61 Posted), (2) SEVEN ELEVEN ($4.70 Pending), (3) PICNICRAND AIR ($1.04 Pending). Total: $8.35 USD.",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 0,
        "usd_direct": 8.35,
        "usd_charged": 8.35,
        "fx_mode_override": "STATEMENT_ONLY_USD",
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted & Pending)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex CSV & Live Activity 09/26/2026",
    },
    {
        "page": 117,
        "display_id": "T-17",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-27",
        "time": "Dining & Shop",
        "merchant_jp": "MEGAドン・キホーテ ($24.52) & La Soffitta ラ・ソフィッタ ($19.75) — BofA Visa *8577",
        "merchant_en": "MEGA Don Quijote ($24.52) + La Soffitta Trattoria ($19.75) on BofA Visa *8577",
        "item_kanji": "MEGAドン・キホーテ追加購入（$24.52）＋ La Soffitta イタリアン飲食（$19.75）",
        "item_en": "2 Tokyo Purchases on BofA Visa *8577 on Sep 27: MEGA Don Quijote ($24.52) + La Soffitta ($19.75) = $44.27",
        "description_en": "Discovered via @Google Wallet on Bank of America Premium Rewards Visa Signature (*8577) on Sep 27, 2026: (1) MEGAドン・キホーテ ($24.52 Pending, ~¥3,864 JPY), (2) La Soffitta Italian restaurant in Shibuya/Harajuku ($19.75 Pending, ~¥3,112 JPY). Total: $44.27 USD.",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 0,
        "usd_direct": 44.27,
        "usd_charged": 44.27,
        "fx_mode_override": "STATEMENT_ONLY_USD",
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "BofA Visa *8577 (Pending — @Google Wallet)",
        "card_network": "Visa",
        "card_mask": "BofA Visa *8577",
        "receipt_ref": "Google Wallet / BofA *8577 09/27/2026 ($24.52 + $19.75)",
    },
    {
        "page": 118,
        "display_id": "T-18",
        "source_type": "DIGITAL_EMAIL",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-28",
        "time": "Transit",
        "merchant_jp": "Uber (9/28 空港・移動ライドシェア2件 — $39.05 + $42.59)",
        "merchant_en": "Uber — 2 Rides on Sep 28 ($39.05 + $42.59 = $81.64 Pending on Amex *4002)",
        "item_kanji": "Uber 配車2回（$39.05 + $42.59 = $81.64 アメックス保留中）",
        "item_en": "2× Uber Rides on Sep 28, 2026 ($39.05 + $42.59 = $81.64 USD Pending on Amex *4002)",
        "description_en": "Two pending Uber rides on American Express *4002 on Sep 28, 2026 ($39.05 and $42.59 = $81.64 USD total). Discovered on live Amex Account Activity tab.",
        "category": "Airport & Ground Transport",
        "jpy_amount": 0,
        "usd_direct": 81.64,
        "usd_charged": 81.64,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending)",
        "card_network": "Amex",
        "card_mask": "Account Ending 84002",
        "receipt_ref": "Amex Live Activity 09/28/2026 (2× UBER $39.05 + $42.59)",
    },
]

# 26 Scanned Pages from Scanned_20260928-2316.pdf
PDF_PAGES = [
    {
        "page": 1,
        "display_id": "Page 01",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": 6,
        "date": "2026-09-26",
        "time": "01:56",
        "merchant_jp": "カラオケルーム歌広場 渋谷センター街別館",
        "merchant_en": "Karaoke Room Utahiroba Shibuya Center-gai Annex",
        "item_kanji": "インバウンド1時間 (2名)",
        "item_en": "Inbound 1-Hour Karaoke Package (2 Guests)",
        "description_en": "Room 0310 late-night 1-hour karaoke & all-you-can-drink package for 2 guests (01:55–02:55, ¥2,500 × 2, incl. 10% tax ¥454). Paired with CC slip on Page 06. Live @Google Wallet BofA Visa *8577 charge: $31.69 USD (effective rate ¥157.78/$ — beat ECB market by -$0.04 / -0.12%).",
        "category": "Nightlife & Entertainment",
        "jpy_amount": 5000,
        "usd_direct": None,
        "usd_charged": 31.69,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "BofA Visa *8577 (Pending Hold $31.69)",
        "card_network": "Visa",
        "card_mask": "440066******8577",
        "receipt_ref": "Room 0310 / Slip #20329 / BofA *8577 (Utahiroba Shibuy $31.69)",
    },
    {
        "page": 2,
        "display_id": "Page 02",
        "source_type": "SCANNED_PDF",
        "page_type": "PAIRED_SLIP",
        "paired_page": 12,
        "date": "2026-09-26",
        "time": "21:16",
        "merchant_jp": "トウキョウタワー チケットウリバ",
        "merchant_en": "Tokyo Tower Ticket Counter (CC Sales Slip)",
        "item_kanji": "クレジットカード売上票（お客様控）— 東京タワー",
        "item_en": "Credit Card Sales Slip (Paired with Page 12 Itemized Ticket Receipt)",
        "description_en": "Customer copy credit card slip for Tokyo Tower Top Deck Tour (¥3,500 / $22.11 on Amex *4002). Slip #31519, Approval #888858. Excluded from sum to prevent double-counting Page 12.",
        "category": "Paired Credit Card Slip",
        "jpy_amount": 3500,
        "usd_direct": None,
        "usd_charged": 22.11,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Paired w/ Page 12)",
        "card_network": "Amex",
        "card_mask": "379299XXXXX4002",
        "receipt_ref": "Slip #31519 / Auth 888858 ($22.11)",
    },
    {
        "page": 3,
        "display_id": "Page 03",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": 9,
        "date": "2026-09-27",
        "time": "12:14",
        "merchant_jp": "HIGHTIDE STORE MIYASHITA PARK",
        "merchant_en": "HIGHTIDE STORE Miyashita Park (Shibuya South 2F)",
        "item_kanji": "ダイアリーシール（レトロ）",
        "item_en": "Retro Diary Planner Stickers (×1)",
        "description_en": "Japanese retro planner/diary sticker sheet from Fukuoka stationery brand HIGHTIDE at Rayard Miyashita Park South 2F (¥286 incl. 10% tax ¥26). Paired with CC slip on Page 09. Billed on Amex *4002 under mall operator MITSUI FUDOSAN SHOGYO MAN for $1.81 USD (effective rate ¥158.01/$).",
        "category": "Souvenirs, Anime & Stationery",
        "jpy_amount": 286,
        "usd_direct": None,
        "usd_charged": 1.81,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $1.81)",
        "card_network": "Amex",
        "card_mask": "370382*****1240",
        "receipt_ref": "Slip #006003933 / Amex MITSUI FUDOSAN SHOGYO MAN ($1.81)",
    },
    {
        "page": 4,
        "display_id": "Page 04",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-28",
        "time": "21:42",
        "merchant_jp": "MEGAドン・キホーテ 渋谷本店",
        "merchant_en": "MEGA Don Quijote Shibuya Main Store",
        "item_kanji": "GBボディトリマー",
        "item_en": "Mandom GATSBY Body Hair Trimmer",
        "description_en": "JAN 4902806112320 — Mandom GATSBY Body Hair Razor/Trimmer comb attachment for men (¥599 + 10% tax ¥59 = ¥658). Live Amex *4002 charge: DON QUIJOTE $4.16 USD (effective rate ¥158.17/$ — beat ECB market by -$0.03 / -0.82%).",
        "category": "Drugstore & Personal Care",
        "jpy_amount": 658,
        "usd_direct": None,
        "usd_charged": 4.16,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $4.16)",
        "card_network": "Amex",
        "card_mask": "037929XXXXXX4002",
        "receipt_ref": "Receipt #7521 / Auth 861678 / Amex DON QUIJOTE ($4.16)",
    },
    {
        "page": 5,
        "display_id": "Page 05",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-26",
        "time": "18:54",
        "merchant_jp": "ニューバランス 原宿 (SuperComp Rebel / S. LAB SP / レジ袋)",
        "merchant_en": "New Balance Harajuku Flagship Store",
        "item_kanji": "SuperComp Rebel (MREBX9S5 260 D) ・ S. LAB SP (27175002-NC) ・ Shopping Bag",
        "item_en": "New Balance FuelCell SuperComp Rebel Running Shoes (26.0cm D) + Socks + Bag",
        "description_en": "SKU MREBX9S5 (26.0cm width D) FuelCell SuperComp Rebel running shoes (¥21,800) + SKU 27175002-NC S.LAB SP performance socks/accessory (¥800) + Shopping Bag (¥20) + 10% tax (¥2,262) = ¥24,882. POSTED on Amex *4002 (NEW BALANCE TOKYO JP) for $158.55 USD (effective rate ¥156.9347/$).",
        "category": "Apparel & Footwear",
        "jpy_amount": 24882,
        "usd_direct": None,
        "usd_charged": 158.55,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted $158.55)",
        "card_network": "Amex",
        "card_mask": "****4002",
        "receipt_ref": "Reg 3 #5061 / Auth 860808 / Amex CSV 09/26/2026 ($158.55)",
    },
    {
        "page": 6,
        "display_id": "Page 06",
        "source_type": "SCANNED_PDF",
        "page_type": "PAIRED_SLIP",
        "paired_page": 1,
        "date": "2026-09-26",
        "time": "01:56",
        "merchant_jp": "ウタヒロバ シブヤセンターガイベツカン",
        "merchant_en": "Karaoke Utahiroba Shibuya Center-gai Annex (CC Sales Slip)",
        "item_kanji": "クレジットカード売上票（お客様控）— 歌広場",
        "item_en": "Credit Card Sales Slip (Paired with Page 01 Itemized Karaoke Receipt)",
        "description_en": "Customer copy credit card slip for Page 01 Karaoke Room Utahiroba charge (¥5,000 / $31.69 on BofA Visa *8577). Slip #20329, App Code 008668D. Excluded from sum to prevent double-counting Page 01.",
        "category": "Paired Credit Card Slip",
        "jpy_amount": 5000,
        "usd_direct": None,
        "usd_charged": 31.69,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "BofA Visa *8577 (Paired w/ Page 01)",
        "card_network": "Visa",
        "card_mask": "440066******8577",
        "receipt_ref": "Slip #20329 / App 008668D ($31.69)",
    },
    {
        "page": 7,
        "display_id": "Page 07",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-24",
        "time": "21:23",
        "merchant_jp": "マツモトキヨシ 渋谷Part1店",
        "merchant_en": "Matsumoto Kiyoshi Shibuya Part 1 Drugstore",
        "item_kanji": "キュレル薬用クリーム ・ GB ムービングラバー ・ キャリーバッグ白M",
        "item_en": "Kao Curél Medicated Moisture Cream + GATSBY Moving Rubber Hair Wax + Medium Bag",
        "description_en": "Store #0378: (1) Kao Curél Intensive Moisture Care Medicated Cream (¥1,650), (2) Mandom GATSBY Moving Rubber Hair Styling Wax (¥426), (3) Medium White Shopping Bag (¥4) = ¥2,080. POSTED on Amex *4002 (0378MATSUMOTOKIYOSHITOKYO JP) for $13.25 USD (effective rate ¥156.9811/$).",
        "category": "Drugstore & Personal Care",
        "jpy_amount": 2080,
        "usd_direct": None,
        "usd_charged": 13.25,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted $13.25)",
        "card_network": "Amex",
        "card_mask": "379299XXXXX4002",
        "receipt_ref": "Receipt #9853 / Auth 874979 / Amex CSV 09/24/2026 ($13.25)",
    },
    {
        "page": 8,
        "display_id": "Page 08",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": 25,
        "date": "2026-09-27",
        "time": "12:07",
        "merchant_jp": "Editorial Miyashita Park (CREDITS株式会社)",
        "merchant_en": "Editorial Miyashita Park (Rayard Miyashita Park South 2F)",
        "item_kanji": "COMIXYZカード『ウソツキ！ゴクオーくん』チェンジングVer. ・ COMIXYZカード「世紀末」チェンジングVer. ・ COMIXYZカード『運命の巻戻士』3DコラージュVer.",
        "item_en": "3× COMIXYZ Lenticular / 3D Collage Manga Art Cards (Shogakukan CoroCoro)",
        "description_en": "3 collectible Shogakukan COMIXYZ motion/3D manga cards at ¥990 each = ¥2,970. Paired w/ Page 25. Billed on Amex *4002 under mall operator MITSUI FUDOSAN SHOGYO MAN for $18.76 USD (effective rate ¥158.3156/$ — beat ECB market by -$0.09 / -0.46%).",
        "category": "Souvenirs, Anime & Stationery",
        "jpy_amount": 2970,
        "usd_direct": None,
        "usd_charged": 18.76,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $18.76)",
        "card_network": "Amex",
        "card_mask": "370382*****1240",
        "receipt_ref": "Tx #80949 / Slip #011957133 / Amex MITSUI FUDOSAN ($18.76)",
    },
    {
        "page": 9,
        "display_id": "Page 09",
        "source_type": "SCANNED_PDF",
        "page_type": "PAIRED_SLIP",
        "paired_page": 3,
        "date": "2026-09-27",
        "time": "12:13",
        "merchant_jp": "RAYARD MIYASHITA PARK - HIGHTIDE STORE",
        "merchant_en": "HIGHTIDE STORE Miyashita Park (CC Sales Slip)",
        "item_kanji": "クレジットカード売上票（お客様控）— HIGHTIDE STORE",
        "item_en": "Credit Card Sales Slip (Paired with Page 03 Itemized Stationery Receipt)",
        "description_en": "Customer copy NFCpay credit card slip for Page 03 HIGHTIDE Store purchase (¥286 / $1.81 on Amex *4002). Slip #006003933, App Code 0854788. Excluded from sum to prevent double-counting Page 03.",
        "category": "Paired Credit Card Slip",
        "jpy_amount": 286,
        "usd_direct": None,
        "usd_charged": 1.81,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Paired w/ Page 03)",
        "card_network": "Amex",
        "card_mask": "370382*****1240",
        "receipt_ref": "Slip #006003933 / App 0854788 ($1.81)",
    },
    {
        "page": 10,
        "display_id": "Page 10",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-25",
        "time": "00:02",
        "merchant_jp": "MEGAドン・キホーテ 渋谷本店",
        "merchant_en": "MEGA Don Quijote Shibuya Main Store",
        "item_kanji": "フェレロヌテラビーレ ・ SUN STICK ・ ユースキンミッフィーチュ",
        "item_en": "Ferrero Nutella B-ready Bar + UV Sun Stick + Yuskin Hana Miffy Hand Cream",
        "description_en": "3 items: (1) Ferrero Nutella B-ready Wafer Bar (¥139 + 8% tax), (2) UV Sunscreen Stick (¥2,500 + 10% tax), (3) Yuskin Hana Miffy Hand Cream Tube 50g (¥599 + 10% tax) = ¥3,558. POSTED on Amex *4002 (MEGA DON QUIJOTE SHI* JP) for $22.67 USD (effective rate ¥156.9475/$).",
        "category": "Drugstore & Personal Care",
        "jpy_amount": 3558,
        "usd_direct": None,
        "usd_charged": 22.67,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted $22.67)",
        "card_network": "Amex",
        "card_mask": "037929XXXXXX4002",
        "receipt_ref": "Receipt #3341 / Auth 828307 / Amex CSV 09/25/2026 ($22.67)",
    },
    {
        "page": 11,
        "display_id": "Page 11",
        "source_type": "SCANNED_PDF",
        "page_type": "NON_EXPENSE",
        "paired_page": 18,
        "date": "2026-09-24",
        "time": "21:27",
        "merchant_jp": "マツモトキヨシ 渋谷Part1店 (キャンペーン応募券)",
        "merchant_en": "Matsumoto Kiyoshi — Promotional Raffle Slip (Non-Expense)",
        "item_kanji": "マツキヨココカラ × 薬屋のひとりごと 花舞う秘薬探し キャンペーン / オータムSALE",
        "item_en": "Non-Expense: The Apothecary Diaries Promo Raffle Slip (from Page 18 purchase)",
        "description_en": "Not an expense (¥0). Promotional raffle entry slip printed automatically with Receipt #2995 (Page 18) for purchasing ≥¥1,000 during the Matsukiyo × The Apothecary Diaries Autumn Sale.",
        "category": "Non-Expense Coupon / Info",
        "jpy_amount": 0,
        "usd_direct": None,
        "usd_charged": None,
        "card_status": "NON_EXPENSE",
        "payment_method": "N/A (Non-Expense Promo Slip)",
        "card_network": "None",
        "card_mask": None,
        "receipt_ref": "Promo Slip for Receipt #2995 (Page 18)",
    },
    {
        "page": 12,
        "display_id": "Page 12",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": 2,
        "date": "2026-09-26",
        "time": "21:16",
        "merchant_jp": "東京タワー (TOKYO TOWER)",
        "merchant_en": "Tokyo Tower Observatory (FootTown 1F Ticket Counter)",
        "item_kanji": "トップデッキツアー(A) 21:15",
        "item_en": "Tokyo Tower Top Deck Tour (150m & 250m Observatory) — 1 Adult Ticket",
        "description_en": "21:15 timed entry Top Deck Tour ticket for 1 Adult (¥3,500 incl. 10% tax ¥318). Paired with Amex *4002 slip on Page 02. Live Amex *4002 charge: TOKYO TOWER TICKET STAND $22.11 USD (effective rate ¥158.2994/$ — beat ECB market by -$0.10 / -0.45%).",
        "category": "Nightlife & Entertainment",
        "jpy_amount": 3500,
        "usd_direct": None,
        "usd_charged": 22.11,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $22.11)",
        "card_network": "Amex",
        "card_mask": "379299XXXXX4002",
        "receipt_ref": "Purchase #17217890 / Amex TOKYO TOWER TICKET STAND ($22.11)",
    },
    {
        "page": 13,
        "display_id": "Page 13",
        "source_type": "SCANNED_PDF",
        "page_type": "NON_EXPENSE",
        "paired_page": 18,
        "date": "2026-09-24",
        "time": "21:27",
        "merchant_jp": "マツモトキヨシ 渋谷Part1店 (レシートクーポン)",
        "merchant_en": "Matsumoto Kiyoshi — 10% OFF Future Discount Coupon (Non-Expense)",
        "item_kanji": "レシートクーポン 医薬品・化粧品 10% OFF / 食品 5% OFF",
        "item_en": "Non-Expense: 10% OFF Pharmaceuticals & Cosmetics Coupon (Valid Oct 7–18, 2026)",
        "description_en": "Not an expense (¥0). Promotional discount coupon printed with Receipt #2995 (Page 18) offering 10% off medicine/cosmetics and 5% off food on future visits.",
        "category": "Non-Expense Coupon / Info",
        "jpy_amount": 0,
        "usd_direct": None,
        "usd_charged": None,
        "card_status": "NON_EXPENSE",
        "payment_method": "N/A (Non-Expense Coupon)",
        "card_network": "None",
        "card_mask": None,
        "receipt_ref": "Coupon from Receipt #2995 (Page 18)",
    },
    {
        "page": 14,
        "display_id": "Page 14",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-27",
        "time": "16:45",
        "merchant_jp": "牛かつ もと村 原宿店",
        "merchant_en": "Gyukatsu Motomura Harajuku (Beef Cutlet Restaurant)",
        "item_kanji": "牛かつ定食195g小鉢3種 ・ 牛かつ定食260g小鉢3種 ・ 生ビール ・ 茶リティー",
        "item_en": "2× Gyukatsu Beef Cutlet Set Meals (195g & 260g w/ 3 Side Dishes) + Draft Beer + Green Tea",
        "description_en": "Table 3 (2 guests): 195g Gyukatsu Set (¥2,810) + 260g Gyukatsu Set (¥3,290) + Draft Beer (¥800) + Charity Green Tea (¥610) = ¥7,510. Receipt printed クレジット(連動) without card digits — CONFIRMED on Amex *4002 (GYUKATSU MOTOMURA HARAJUK) for $47.44 USD (effective rate ¥158.3052/$ — beat ECB market by -$0.22 / -0.45%).",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 7510,
        "usd_direct": None,
        "usd_charged": 47.44,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $47.44 — クレジット連動)",
        "card_network": "Amex",
        "card_mask": "Amex *4002 (クレジット連動)",
        "receipt_ref": "Receipt #143443 / Amex GYUKATSU MOTOMURA HARAJUK ($47.44)",
    },
    {
        "page": 15,
        "display_id": "Page 15",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": 21,
        "date": "2026-09-26",
        "time": "22:04",
        "merchant_jp": "TOKYO TOWER OFFICIAL SHOP GALAXY",
        "merchant_en": "Tokyo Tower Official Shop GALAXY (FootTown 3F)",
        "item_kanji": "のびねこ東京タワー ・ キャストチャーム ・ TOKYO TOWER ミネラルウォーター2nd",
        "item_en": "Nobineko Tokyo Tower Plush Keychain + Cast Metal Charm + Souvenir Tower Water Bottle",
        "description_en": "3 items: (1) Nobineko Stretchy Cat Plush Mascot Tokyo Tower Ver. (¥830), (2) Tokyo Tower Cast Metal Charm (¥500), (3) Tokyo Tower Shaped Mineral Water Bottle 2nd Ed. (¥440) = ¥1,770. Paired w/ Page 21 CC slip. Live Amex *4002 charge: TOKYO TOWER THE SKY $11.18 USD (effective rate ¥158.3184/$ — beat ECB market by -$0.05 / -0.46%).",
        "category": "Souvenirs, Anime & Stationery",
        "jpy_amount": 1770,
        "usd_direct": None,
        "usd_charged": 11.18,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $11.18)",
        "card_network": "Amex",
        "card_mask": "379299XXXXX4002",
        "receipt_ref": "Slip #55925 / Amex TOKYO TOWER THE SKY ($11.18)",
    },
    {
        "page": 16,
        "display_id": "Page 16",
        "source_type": "SCANNED_PDF",
        "page_type": "NON_EXPENSE",
        "paired_page": "T-02",
        "date": "2026-09-24",
        "time": "Check-in",
        "merchant_jp": "all day place shibuya (オールデイプレイス渋谷)",
        "merchant_en": "all day place shibuya Hotel — Room #708 Welcome & Wi-Fi Slip (Non-Expense)",
        "item_kanji": "WELCOME! 宿泊案内・Wi-Fi・カフェ優待券 (708号室 CHAVEZ JESUS様)",
        "item_en": "Non-Expense: Hotel Room #708 Key Card Sleeve / Wi-Fi & Guest Perks Sheet (Sep 24–29)",
        "description_en": "Not an expense receipt (¥0 on slip; pre-paid ¥169,810 / $1,083.87 net on T-02 & T-03). Hotel welcome information sheet for CHAVEZ JESUS (Room #708, Stay: 2026/09/24 – 2026/09/29, 1 guest) with Wi-Fi credentials (adp-guest) and 10% off Mikkeller Kiosk / ABOUT LIFE COFFEE.",
        "category": "Non-Expense Coupon / Info",
        "jpy_amount": 0,
        "usd_direct": None,
        "usd_charged": None,
        "card_status": "NON_EXPENSE",
        "payment_method": "N/A (Hotel Room #708 Info Sheet — Paid on T-02/T-03)",
        "card_network": "None",
        "card_mask": None,
        "receipt_ref": "Room #708 (2026/09/24 - 09/29)",
    },
    {
        "page": 17,
        "display_id": "Page 17",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-26",
        "time": "04:37",
        "merchant_jp": "渋谷NAVY / adLOVE / T2",
        "merchant_en": "T2 Shibuya / NAVY Nightclub & Lounge (Shibuya)",
        "item_kanji": "渋谷NAVY/adLOVE/T2（ナイトクラブ・テーブル・飲食代）",
        "item_en": "Nightclub VIP Table / Bottle Service & Drinks at T2 Shibuya (NAVY)",
        "description_en": "Late-night charge (04:37 AM JST) at Shibuya NAVY / adLOVE / T2 International Nightclub & Lounge in Shibuya (¥60,700). Paid with American Express XXXXXXXXXXX4002 (CHAVEZ JESUS), Slip #05751, Approval #841055. Processed via JCB Group acquirer — the only receipt out of 17 not yet batch-settled to Amex online.",
        "category": "Nightlife & Entertainment",
        "jpy_amount": 60700,
        "usd_direct": None,
        "usd_charged": None,
        "card_status": "AWAITING_MERCHANT_BATCH",
        "payment_method": "Amex *4002 (Awaiting JCB Acquirer Batch)",
        "card_network": "Amex",
        "card_mask": "XXXXXXXXXXX4002",
        "receipt_ref": "Slip #05751 / Auth 841055 (JCB Acquirer Batch)",
    },
    {
        "page": 18,
        "display_id": "Page 18",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-24",
        "time": "21:27",
        "merchant_jp": "マツモトキヨシ 渋谷Part1店",
        "merchant_en": "Matsumoto Kiyoshi Shibuya Part 1 Drugstore",
        "item_kanji": "NONIOクリアハーブミント ・ mkデンタルフロス ・ ゴクボソハブラシ",
        "item_en": "Lion NONIO Toothpaste Clear Herb Mint + Matsukiyo Dental Floss + Ultra-Fine Toothbrush",
        "description_en": "Store #0378 (4 mins after Page 07): (1) Lion NONIO Clear Herb Mint Toothpaste (¥273), (2) Matsukiyo Dental Floss (¥327), (3) Ultra-Fine Bristle Toothbrush (¥767) = ¥1,367. POSTED on Amex *4002 (0378MATSUMOTOKIYOSHITOKYO JP) for $8.71 USD (effective rate ¥156.9460/$).",
        "category": "Drugstore & Personal Care",
        "jpy_amount": 1367,
        "usd_direct": None,
        "usd_charged": 8.71,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted $8.71)",
        "card_network": "Amex",
        "card_mask": "379299XXXXX4002",
        "receipt_ref": "Receipt #2995 / Auth 852178 / Amex CSV 09/24/2026 ($8.71)",
    },
    {
        "page": 19,
        "display_id": "Page 19",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-23",
        "time": "13:10",
        "merchant_jp": "Paradies Lagardère — DTW Airport (米国デトロイト空港)",
        "merchant_en": "Paradies Lagardère — Detroit Metro Airport (DTW #1164 Corktown Place)",
        "item_kanji": "LSAVER 5 FLAVS 20PK（ライフセーバーズ 5フレーバー キャンディ）",
        "item_en": "Life Savers 5 Flavors Hard Candy Roll (DTW Airport Departure Transit)",
        "description_en": "US airport transit purchase en route to Tokyo at Detroit Metro Airport (DTW Corktown Place #1164): Life Savers 5 Flavors Candy ($2.91 + 6% MI tax $0.18 = $3.09 USD). Confirmed POSTED on BofA Visa *8577 via @Google Wallet.",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 0,
        "usd_direct": 3.09,
        "usd_charged": 3.09,
        "card_status": "POSTED",
        "payment_method": "BofA Visa *8577 (Posted $3.09)",
        "card_network": "Visa",
        "card_mask": "************8936 (BofA *8577)",
        "receipt_ref": "Tx #350226026 / Google Wallet BofA *8577 ($3.09)",
    },
    {
        "page": 20,
        "display_id": "Page 20",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-25",
        "time": "13:00",
        "merchant_jp": "渋谷ロフト (Shibuya LOFT)",
        "merchant_en": "Shibuya LOFT Lifestyle Department Store",
        "item_kanji": "オーズナリーレストア (1点)",
        "item_en": "O's Nary Restore / Personal Care & Lifestyle Item (1 Unit)",
        "description_en": "Purchased at Shibuya LOFT (Tel: 03-3462-3807): 1× O's Nary Restore item (¥2,200 + 10% tax ¥220 = ¥2,420). Paid via BofA Visa *8577. Live @Google Wallet charge: Loft $15.34 USD (effective rate ¥157.7575/$ — beat ECB market by -$0.02 / -0.11%).",
        "category": "Drugstore & Personal Care",
        "jpy_amount": 2420,
        "usd_direct": None,
        "usd_charged": 15.34,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "BofA Visa *8577 (Pending Hold $15.34)",
        "card_network": "Visa",
        "card_mask": "440066XXXXXX8577",
        "receipt_ref": "Slip #47064 / Google Wallet BofA *8577 (Loft $15.34)",
    },
    {
        "page": 21,
        "display_id": "Page 21",
        "source_type": "SCANNED_PDF",
        "page_type": "PAIRED_SLIP",
        "paired_page": 15,
        "date": "2026-09-26",
        "time": "22:04",
        "merchant_jp": "TOKYO TOWER OFFICIAL SH",
        "merchant_en": "Tokyo Tower Official Shop GALAXY (CC Sales Slip)",
        "item_kanji": "クレジットカード売上票（お客様控）— TOKYO TOWER OFFICIAL SHOP",
        "item_en": "Credit Card Sales Slip (Paired with Page 15 Itemized Souvenir Receipt)",
        "description_en": "Customer copy credit card slip for Page 15 Tokyo Tower Official Shop Galaxy purchase (¥1,770 / $11.18 on Amex *4002). Slip #55925, Approval #840215. Excluded from sum to prevent double-counting Page 15.",
        "category": "Paired Credit Card Slip",
        "jpy_amount": 1770,
        "usd_direct": None,
        "usd_charged": 11.18,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Paired w/ Page 15)",
        "card_network": "Amex",
        "card_mask": "379299XXXXX4002",
        "receipt_ref": "Slip #55925 / Auth 840215 ($11.18)",
    },
    {
        "page": 22,
        "display_id": "Page 22",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-26",
        "time": "17:36",
        "merchant_jp": "ファミリーマート 神宮前店",
        "merchant_en": "FamilyMart Jingumae Convenience Store (Harajuku)",
        "item_kanji": "ウコンの力超MAX",
        "item_en": "House Wellness Foods 'Ukon no Chikara Super MAX' Turmeric Recovery Drink",
        "description_en": "Convenience store purchase at FamilyMart Jingumae: 1× Ukon no Chikara Super MAX turmeric recovery drink (¥581 incl. 8% tax). POSTED on Amex *4002 (FAMILY MART * JP) for $3.70 USD (effective rate ¥157.0270/$).",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 581,
        "usd_direct": None,
        "usd_charged": 3.70,
        "card_status": "POSTED",
        "payment_method": "Amex *4002 (Posted $3.70)",
        "card_network": "Amex",
        "card_mask": "**** **** **** 002",
        "receipt_ref": "No. 4248027 / Auth 899358 / Amex CSV 09/26/2026 ($3.70)",
    },
    {
        "page": 23,
        "display_id": "Page 23",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-26",
        "time": "18:25",
        "merchant_jp": "ちょい呑み食堂 まってぃーに / まるや 二号店 (原宿かつ畔)",
        "merchant_en": "Choinomi Shokudo Martini / Maruya 2nd Branch (Harajuku Katsuhan)",
        "item_kanji": "席料 ・ D和牛丼 ・ ゼロコーラ zero cok",
        "item_en": "Wagyu Beef Donburi Bowl + Coca-Cola Zero + Table Seating Charge",
        "description_en": "Dinner for 1 in Harajuku: Table Charge (¥165) + Wagyu Beef Bowl (¥2,420) + Coca-Cola Zero (¥429) = ¥3,014. Receipt printed クレジット 1 without card digits — CONFIRMED on Amex *4002 under parent restaurant KATSUHAN HARAJUKUTEN for $19.04 USD (effective rate ¥158.2983/$ — beat ECB market by -$0.09 / -0.45%).",
        "category": "Dining, Food & Convenience",
        "jpy_amount": 3014,
        "usd_direct": None,
        "usd_charged": 19.04,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $19.04 — クレジット 1)",
        "card_network": "Amex",
        "card_mask": "Amex *4002 (KATSUHAN HARAJUKUTEN)",
        "receipt_ref": "Table #4772 / Amex KATSUHAN HARAJUKUTEN ($19.04)",
    },
    {
        "page": 24,
        "display_id": "Page 24",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-27",
        "time": "10:25",
        "merchant_jp": "HAPPY ONE SOUVENIR SHOP",
        "merchant_en": "Happy One Souvenir Shop (Tokyo — Charged to BofA Visa *8577)",
        "item_kanji": "部門01（お土産品 ¥6,980） ・ 部門01（袋 ¥20）",
        "item_en": "Japanese Souvenir Gift Item (¥6,980) + Shopping Bag (¥20)",
        "description_en": "SOLVED VIA @GOOGLE WALLET: Although the shop clerk pressed the 現金 (Cash) button on their standalone cash register to print this receipt (¥7,000), your Bank of America Visa *8577 statement shows 'happyOne — $44.61 USD (Pending Purchase)' on Sep 26 (US time for Sep 27 10:25 JST)! Effective card rate: ¥156.9155/$ (+$0.19 / +0.43% vs. ECB). ZERO receipts in the PDF were paid with cash!",
        "category": "Souvenirs, Anime & Stationery",
        "jpy_amount": 7000,
        "usd_direct": None,
        "usd_charged": 44.61,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "BofA Visa *8577 (Pending $44.61 — Register Printed 現金)",
        "card_network": "Visa",
        "card_mask": "BofA Visa *8577 (happyOne $44.61)",
        "receipt_ref": "Receipt #3739 / Google Wallet BofA *8577 (happyOne $44.61)",
    },
    {
        "page": 25,
        "display_id": "Page 25",
        "source_type": "SCANNED_PDF",
        "page_type": "PAIRED_SLIP",
        "paired_page": 8,
        "date": "2026-09-27",
        "time": "12:07",
        "merchant_jp": "RAYARD MIYASHITA PARK - The Editorial",
        "merchant_en": "Editorial Miyashita Park (CC Sales Slip)",
        "item_kanji": "クレジットカード売上票（お客様控）— The Editorial",
        "item_en": "Credit Card Sales Slip (Paired with Page 08 Itemized COMIXYZ Receipt)",
        "description_en": "Customer copy NFCpay credit card slip for Page 08 Editorial Miyashita Park purchase (¥2,970 / $18.76 on Amex *4002). Slip #011957133, App Code 0878975. Excluded from sum to prevent double-counting Page 08.",
        "category": "Paired Credit Card Slip",
        "jpy_amount": 2970,
        "usd_direct": None,
        "usd_charged": 18.76,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Paired w/ Page 08)",
        "card_network": "Amex",
        "card_mask": "370382*****1240",
        "receipt_ref": "Slip #011957133 / App 0878975 ($18.76)",
    },
    {
        "page": 26,
        "display_id": "Page 26",
        "source_type": "SCANNED_PDF",
        "page_type": "EXPENSE",
        "paired_page": None,
        "date": "2026-09-27",
        "time": "22:35",
        "merchant_jp": "MEGAドン・キホーテ 渋谷本店",
        "merchant_en": "MEGA Don Quijote Shibuya Main Store",
        "item_kanji": "歯磨き堂FP Sミント ・ ユースキンミッフィーチューブ×2 ・ イープレミアムワイド ・ OC硬めモフらしコンパク ・ OC濃密極細毛ブラシC ・ ステンドしおり 鯉2匹 ・ ヴァセリンリップ オリジ ・ シングルSMチョコA ・ レジ袋 ・ ソフト大福 イチゴ",
        "item_en": "11 Items: Hamigakido Toothpaste, 2× Yuskin Miffy Cream, 3× Toothbrushes, Koi Stained-Glass Bookmark, Vaseline Lip, Chocolate & Strawberry Daifuku Mochi",
        "description_en": "11 items totaling ¥8,753 (Subtotal ¥7,967 + Tax ¥786). Live Amex *4002 charge: DON QUIJOTE $55.29 USD (effective rate ¥158.3107/$ — beat ECB market by -$0.25 / -0.45%).",
        "category": "Drugstore & Personal Care",
        "jpy_amount": 8753,
        "usd_direct": None,
        "usd_charged": 55.29,
        "card_status": "PENDING_CARD_HOLD",
        "payment_method": "Amex *4002 (Pending Hold $55.29)",
        "card_network": "Amex",
        "card_mask": "037929XXXXXX4002",
        "receipt_ref": "Receipt #5598 / Auth 837553 / Amex DON QUIJOTE ($55.29)",
    },
]

PAGES = DIGITAL_EXPENSES + PDF_PAGES

for p in PAGES:
    ms = FX_MULTI_SOURCES.get(p["date"], {"ecb": 157.59, "yahoo_ny": 157.45, "currency_api": 157.30})
    p["fx_rate_market"] = ms["ecb"]
    p["fx_rate_yahoo_ny"] = ms["yahoo_ny"]
    p["fx_rate_currency_api"] = ms["currency_api"]

    if p.get("fx_mode_override"):
        p["fx_mode"] = p["fx_mode_override"]
        p["usd_market"] = round(p["usd_direct"], 2)
        p["usd_market_yahoo"] = round(p["usd_direct"], 2)
        p["usd_market_capi"] = round(p["usd_direct"], 2)
    elif p["usd_direct"] is not None:
        p["fx_mode"] = "DIRECT_USD"
        p["usd_market"] = round(p["usd_direct"], 2)
        p["usd_market_yahoo"] = round(p["usd_direct"], 2)
        p["usd_market_capi"] = round(p["usd_direct"], 2)
    elif p["jpy_amount"] != 0:
        p["fx_mode"] = "FOREIGN_JPY"
        p["usd_market"] = round(p["jpy_amount"] / ms["ecb"], 2)
        p["usd_market_yahoo"] = round(p["jpy_amount"] / ms["yahoo_ny"], 2)
        p["usd_market_capi"] = round(p["jpy_amount"] / ms["currency_api"], 2)
    else:
        p["fx_mode"] = "NON_EXPENSE"
        p["usd_market"] = 0.0
        p["usd_market_yahoo"] = 0.0
        p["usd_market_capi"] = 0.0

    if p["usd_charged"] is not None and p["fx_mode"] == "FOREIGN_JPY":
        p["usd_diff"] = round(p["usd_charged"] - p["usd_market"], 2)
        p["usd_diff_yahoo"] = round(p["usd_charged"] - p["usd_market_yahoo"], 2)
        p["usd_diff_capi"] = round(p["usd_charged"] - p["usd_market_capi"], 2)
        p["card_effective_rate"] = round(p["jpy_amount"] / p["usd_charged"], 4)
    else:
        p["usd_diff"] = None
        p["usd_diff_yahoo"] = None
        p["usd_diff_capi"] = None
        p["card_effective_rate"] = None

    if p["source_type"] == "SCANNED_PDF":
        p["image_url"] = f"/static/pages/page_{p['page']:02d}.png"
    else:
        p["image_url"] = None

expenses = [p for p in PAGES if p["page_type"] == "EXPENSE"]
pdf_expenses = [p for p in expenses if p["source_type"] == "SCANNED_PDF"]
digital_expenses = [p for p in expenses if p["source_type"] == "DIGITAL_EMAIL"]

total_jpy = sum(p["jpy_amount"] for p in expenses)
total_usd_market = round(sum(p["usd_market"] for p in expenses), 2)
total_usd_yahoo = round(sum(p["usd_market_yahoo"] for p in expenses), 2)
total_usd_capi = round(sum(p["usd_market_capi"] for p in expenses), 2)
total_usd_effective = round(sum(p["usd_charged"] if p["usd_charged"] is not None else p["usd_market"] for p in expenses), 2)

pdf_jpy = sum(p["jpy_amount"] for p in pdf_expenses)
pdf_usd_market = round(sum(p["usd_market"] for p in pdf_expenses), 2)
pdf_usd_effective = round(sum(p["usd_charged"] if p["usd_charged"] is not None else p["usd_market"] for p in pdf_expenses), 2)

digital_jpy = sum(p["jpy_amount"] for p in digital_expenses)
digital_usd_market = round(sum(p["usd_market"] for p in digital_expenses), 2)
digital_usd_charged = round(sum(p["usd_charged"] for p in digital_expenses if p["usd_charged"] is not None), 2)

cat_totals = {}
for p in expenses:
    c = p["category"]
    cat_totals.setdefault(c, {"count": 0, "jpy": 0, "usd_market": 0.0, "usd_effective": 0.0})
    cat_totals[c]["count"] += 1
    cat_totals[c]["jpy"] += p["jpy_amount"]
    cat_totals[c]["usd_market"] = round(cat_totals[c]["usd_market"] + p["usd_market"], 2)
    eff = p["usd_charged"] if p["usd_charged"] is not None else p["usd_market"]
    cat_totals[c]["usd_effective"] = round(cat_totals[c]["usd_effective"] + eff, 2)

card_totals = {}
for p in expenses:
    cn = p["card_network"]
    card_totals.setdefault(cn, {"count": 0, "jpy": 0, "usd_market": 0.0, "usd_effective": 0.0})
    card_totals[cn]["count"] += 1
    card_totals[cn]["jpy"] += p["jpy_amount"]
    card_totals[cn]["usd_market"] = round(card_totals[cn]["usd_market"] + p["usd_market"], 2)
    eff = p["usd_charged"] if p["usd_charged"] is not None else p["usd_market"]
    card_totals[cn]["usd_effective"] = round(card_totals[cn]["usd_effective"] + eff, 2)

out = {
    "document": "Scanned_20260928-2316.pdf + Gmail, Amex *4002 & BofA Visa *8577 (@Google Wallet)",
    "drive_folder": "jchavezar@gmail.com -> 10 Trips / Japan-2026 + Gmail + Google Wallet + Amex",
    "total_records": len(PAGES),
    "total_pages": len(PDF_PAGES),
    "digital_records": len(DIGITAL_EXPENSES),
    "unique_expense_pages": len(expenses),
    "pdf_expense_pages": len(pdf_expenses),
    "paired_slip_pages": sum(1 for p in PAGES if p["page_type"] == "PAIRED_SLIP"),
    "non_expense_pages": sum(1 for p in PAGES if p["page_type"] == "NON_EXPENSE"),
    "total_jpy": total_jpy,
    "total_usd_market": total_usd_market,
    "total_usd_yahoo": total_usd_yahoo,
    "total_usd_capi": total_usd_capi,
    "total_usd_effective": total_usd_effective,
    "pdf_jpy": pdf_jpy,
    "pdf_usd_market": pdf_usd_market,
    "pdf_usd_effective": pdf_usd_effective,
    "digital_jpy": digital_jpy,
    "digital_usd_market": digital_usd_market,
    "digital_usd_charged": digital_usd_charged,
    "fx_rates": FX_RATES,
    "fx_multi_sources": FX_MULTI_SOURCES,
    "category_breakdown": cat_totals,
    "payment_network_breakdown": card_totals,
    "pages": PAGES,
}

dest = Path(__file__).parent / "receipts_ground_truth.json"
dest.write_text(json.dumps(out, indent=2, ensure_ascii=False))
print(f"Total Audited Records: {out['total_records']} ({len(DIGITAL_EXPENSES)} Digital/Card Trip Records + 26 Scanned PDF Pages)")
print(f"Receipt-Backed Foreign JPY Spend: ¥{total_jpy:,}")
print(f"Multi-Source Market Totals -> ECB: ${total_usd_market:,.2f} | Yahoo NY: ${total_usd_yahoo:,.2f} | Currency-API: ${total_usd_capi:,.2f} | Effective Charged: ${total_usd_effective:,.2f}")
