FROM python:3.10-slim

RUN pip install -U pip
RUN pip install google-cloud-aiplatform && \
    pip install google-cloud-pipeline-components && \
    pip install kfp

COPY pipelines-flex/tensorflow/tabular/pipeline.py pipeline.py
COPY variables.py variables.py