FROM python:3.10-slim

RUN pip install -U pip
RUN pip install google-cloud-aiplatform && \
    google-cloud-pipeline-components && \
    pip install kfp

COPY pipeline.py pipeline.py
COPY variables.py variables.py