FROM python:3.10-slim

RUN pip install -U pip
RUN pip install google-cloud-aiplatform && \
    pip install google-cloud-pipeline-components && \
    pip install kfp

COPY vertex-ai-samples/pipelines-flex/tensorflow/tabular/pipeline.py pipeline.py
COPY vertex-ai-samples/pipelines-flex/tensorflow/tabular/variables.py variables.py